(function($){
  function disableSaveButton() {
    $(this.refs.imgSpinner.getDOMNode()).show();
    $(this.refs.btnSave.getDOMNode()).attr('disabled', true);
  }
  function enableSaveButton() {
    $(this.refs.imgSpinner.getDOMNode()).hide();
    $(this.refs.btnSave.getDOMNode()).attr('disabled', false);
  }

  function onSave() {
    if(this.props.onSave) {
      disableSaveButton.call(this);
      var data = {};
      data.name = this.refs.name.getDOMNode().value;
      data.description = this.refs.description.getDOMNode().value;
      data.is_public = this.refs.is_public.getDOMNode().checked;
      this.props.onSave(data);
    }
  }

  function onCancel() {
    if (this.props.onCancel) {
      this.props.onCancel();
    }
  }

  var DeviceEdit = React.createClass({
    setDevice: function(device) {
      enableSaveButton.call(this);

      this.refs.name.getDOMNode().value = device.name;
      this.refs.description.getDOMNode().value = device.description;
      this.refs.is_public.getDOMNode().checked = device.is_public;
    },
    componentDidMount: function() {
      console.log('DeviceEdit: component did mount');
      enableSaveButton.call(this);
    },
    render: function() {
      return (
        <div ng-show="edition">
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input type="text" ref="name" className="form-control" placeholder="e.g. Light Switch" />
          </div>
          <div className="form-group">
            <label className="description">Description</label>
            <textarea className="form-control" ref="description">
            </textarea>
          </div>
          <div className="checkbox">
            <label>
              <input type="checkbox" ref="is_public" />
              Device is public
            </label>
            <span className="help-block">
              If Device is public, the data generated by it will be shared under CC0 1.0
            </span>
          </div>
          <div className="form-group">
            <button className="btn btn-light" onClick={onSave.bind(this)} ref="btnSave">
              <i className="fa fa-spinner fa-spin" ref="imgSpinner"></i> Save Changes
            </button>
            &nbsp;&nbsp;&nbsp;
            <a href="javascript:void(0)" onClick={onCancel.bind(this)}>Cancel</a>
          </div>
        </div>
      );
    }
  });
  window.DeviceEdit = DeviceEdit;
}).call(document, jQuery);
