<?php
class CountrySeeder extends Seeder {
    public function run() {
        Country::create(array("code" => "AF", "name" => "Afghanistan"));
        Country::create(array("code" => "AL", "name" => "Albania"));
        Country::create(array("code" => "DZ", "name" => "Algeria"));
        Country::create(array("code" => "AS", "name" => "American Samoa"));
        Country::create(array("code" => "AD", "name" => "Andorra"));
        Country::create(array("code" => "AG", "name" => "Angola"));
        Country::create(array("code" => "AI", "name" => "Anguilla"));
        Country::create(array("code" => "AG", "name" => "Antigua and Barbuda"));
        Country::create(array("code" => "AR", "name" => "Argentina"));
        Country::create(array("code" => "AA", "name" => "Armenia"));
        Country::create(array("code" => "AW", "name" => "Aruba"));
        Country::create(array("code" => "AU", "name" => "Australia"));
        Country::create(array("code" => "AT", "name" => "Austria"));
        Country::create(array("code" => "AZ", "name" => "Azerbaijan"));
        Country::create(array("code" => "BS", "name" => "Bahamas"));
        Country::create(array("code" => "BH", "name" => "Bahrain"));
        Country::create(array("code" => "BD", "name" => "Bangladesh"));
        Country::create(array("code" => "BB", "name" => "Barbados"));
        Country::create(array("code" => "BY", "name" => "Belarus"));
        Country::create(array("code" => "BE", "name" => "Belgium"));
        Country::create(array("code" => "BZ", "name" => "Belize"));
        Country::create(array("code" => "BJ", "name" => "Benin"));
        Country::create(array("code" => "BM", "name" => "Bermuda"));
        Country::create(array("code" => "BT", "name" => "Bhutan"));
        Country::create(array("code" => "BO", "name" => "Bolivia"));
        Country::create(array("code" => "BL", "name" => "Bonaire"));
        Country::create(array("code" => "BA", "name" => "Bosnia and Herzegovina"));
        Country::create(array("code" => "BW", "name" => "Botswana"));
        Country::create(array("code" => "BR", "name" => "Brazil"));
        Country::create(array("code" => "BC", "name" => "British Indian Ocean Ter"));
        Country::create(array("code" => "BN", "name" => "Brunei"));
        Country::create(array("code" => "BG", "name" => "Bulgaria"));
        Country::create(array("code" => "BF", "name" => "Burkina Faso"));
        Country::create(array("code" => "BI", "name" => "Burundi"));
        Country::create(array("code" => "KH", "name" => "Cambodia"));
        Country::create(array("code" => "CM", "name" => "Cameroon"));
        Country::create(array("code" => "CA", "name" => "Canada"));
        Country::create(array("code" => "IC", "name" => "Canary Islands"));
        Country::create(array("code" => "CV", "name" => "Cape Verde"));
        Country::create(array("code" => "KY", "name" => "Cayman Islands"));
        Country::create(array("code" => "CF", "name" => "Central African Republic"));
        Country::create(array("code" => "TD", "name" => "Chad"));
        Country::create(array("code" => "CD", "name" => "Channel Islands"));
        Country::create(array("code" => "CL", "name" => "Chile"));
        Country::create(array("code" => "CN", "name" => "China"));
        Country::create(array("code" => "CI", "name" => "Christmas Island"));
        Country::create(array("code" => "CS", "name" => "Cocos Island"));
        Country::create(array("code" => "CO", "name" => "Colombia"));
        Country::create(array("code" => "CC", "name" => "Comoros"));
        Country::create(array("code" => "CG", "name" => "Congo"));
        Country::create(array("code" => "CK", "name" => "Cook Islands"));
        Country::create(array("code" => "CR", "name" => "Costa Rica"));
        Country::create(array("code" => "CT", "name" => "Cote D'Ivoire"));
        Country::create(array("code" => "HR", "name" => "Croatia"));
        Country::create(array("code" => "CU", "name" => "Cuba"));
        Country::create(array("code" => "CB", "name" => "Curacao"));
        Country::create(array("code" => "CY", "name" => "Cyprus"));
        Country::create(array("code" => "CZ", "name" => "Czech Republic"));
        Country::create(array("code" => "DK", "name" => "Denmark"));
        Country::create(array("code" => "DJ", "name" => "Djibouti"));
        Country::create(array("code" => "DM", "name" => "Dominica"));
        Country::create(array("code" => "DO", "name" => "Dominican Republic"));
        Country::create(array("code" => "TM", "name" => "East Timor"));
        Country::create(array("code" => "EC", "name" => "Ecuador"));
        Country::create(array("code" => "EG", "name" => "Egypt"));
        Country::create(array("code" => "SV", "name" => "El Salvador"));
        Country::create(array("code" => "GQ", "name" => "Equatorial Guinea"));
        Country::create(array("code" => "ER", "name" => "Eritrea"));
        Country::create(array("code" => "EE", "name" => "Estonia"));
        Country::create(array("code" => "ET", "name" => "Ethiopia"));
        Country::create(array("code" => "FA", "name" => "Falkland Islands"));
        Country::create(array("code" => "FO", "name" => "Faroe Islands"));
        Country::create(array("code" => "FJ", "name" => "Fiji"));
        Country::create(array("code" => "FI", "name" => "Finland"));
        Country::create(array("code" => "FR", "name" => "France"));
        Country::create(array("code" => "GF", "name" => "French Guiana"));
        Country::create(array("code" => "PF", "name" => "French Polynesia"));
        Country::create(array("code" => "FS", "name" => "French Southern Ter"));
        Country::create(array("code" => "GA", "name" => "Gabon"));
        Country::create(array("code" => "GM", "name" => "Gambia"));
        Country::create(array("code" => "GE", "name" => "Georgia"));
        Country::create(array("code" => "DE", "name" => "Germany"));
        Country::create(array("code" => "GH", "name" => "Ghana"));
        Country::create(array("code" => "GI", "name" => "Gibraltar"));
        Country::create(array("code" => "GB", "name" => "Great Britain"));
        Country::create(array("code" => "GR", "name" => "Greece"));
        Country::create(array("code" => "GL", "name" => "Greenland"));
        Country::create(array("code" => "GD", "name" => "Grenada"));
        Country::create(array("code" => "GP", "name" => "Guadeloupe"));
        Country::create(array("code" => "GU", "name" => "Guam"));
        Country::create(array("code" => "GT", "name" => "Guatemala"));
        Country::create(array("code" => "GN", "name" => "Guinea"));
        Country::create(array("code" => "GY", "name" => "Guyana"));
        Country::create(array("code" => "HT", "name" => "Haiti"));
        Country::create(array("code" => "HW", "name" => "Hawaii"));
        Country::create(array("code" => "HN", "name" => "Honduras"));
        Country::create(array("code" => "HK", "name" => "Hong Kong"));
        Country::create(array("code" => "HU", "name" => "Hungary"));
        Country::create(array("code" => "IS", "name" => "Iceland"));
        Country::create(array("code" => "IN", "name" => "India"));
        Country::create(array("code" => "ID", "name" => "Indonesia"));
        Country::create(array("code" => "IA", "name" => "Iran"));
        Country::create(array("code" => "IQ", "name" => "Iraq"));
        Country::create(array("code" => "IR", "name" => "Ireland"));
        Country::create(array("code" => "IM", "name" => "Isle of Man"));
        Country::create(array("code" => "IL", "name" => "Israel"));
        Country::create(array("code" => "IT", "name" => "Italy"));
        Country::create(array("code" => "JM", "name" => "Jamaica"));
        Country::create(array("code" => "JP", "name" => "Japan"));
        Country::create(array("code" => "JO", "name" => "Jordan"));
        Country::create(array("code" => "KZ", "name" => "Kazakhstan"));
        Country::create(array("code" => "KE", "name" => "Kenya"));
        Country::create(array("code" => "KI", "name" => "Kiribati"));
        Country::create(array("code" => "NK", "name" => "Korea North"));
        Country::create(array("code" => "KS", "name" => "Korea South"));
        Country::create(array("code" => "KW", "name" => "Kuwait"));
        Country::create(array("code" => "KG", "name" => "Kyrgyzstan"));
        Country::create(array("code" => "LA", "name" => "Laos"));
        Country::create(array("code" => "LV", "name" => "Latvia"));
        Country::create(array("code" => "LB", "name" => "Lebanon"));
        Country::create(array("code" => "LS", "name" => "Lesotho"));
        Country::create(array("code" => "LR", "name" => "Liberia"));
        Country::create(array("code" => "LY", "name" => "Libya"));
        Country::create(array("code" => "LI", "name" => "Liechtenstein"));
        Country::create(array("code" => "LT", "name" => "Lithuania"));
        Country::create(array("code" => "LU", "name" => "Luxembourg"));
        Country::create(array("code" => "MO", "name" => "Macau"));
        Country::create(array("code" => "MK", "name" => "Macedonia"));
        Country::create(array("code" => "MG", "name" => "Madagascar"));
        Country::create(array("code" => "MY", "name" => "Malaysia"));
        Country::create(array("code" => "MW", "name" => "Malawi"));
        Country::create(array("code" => "MV", "name" => "Maldives"));
        Country::create(array("code" => "ML", "name" => "Mali"));
        Country::create(array("code" => "MT", "name" => "Malta"));
        Country::create(array("code" => "MH", "name" => "Marshall Islands"));
        Country::create(array("code" => "MQ", "name" => "Martinique"));
        Country::create(array("code" => "MR", "name" => "Mauritania"));
        Country::create(array("code" => "MU", "name" => "Mauritius"));
        Country::create(array("code" => "ME", "name" => "Mayotte"));
        Country::create(array("code" => "MX", "name" => "Mexico"));
        Country::create(array("code" => "MI", "name" => "Midway Islands"));
        Country::create(array("code" => "MD", "name" => "Moldova"));
        Country::create(array("code" => "MC", "name" => "Monaco"));
        Country::create(array("code" => "MN", "name" => "Mongolia"));
        Country::create(array("code" => "MS", "name" => "Montserrat"));
        Country::create(array("code" => "MA", "name" => "Morocco"));
        Country::create(array("code" => "MZ", "name" => "Mozambique"));
        Country::create(array("code" => "MM", "name" => "Myanmar"));
        Country::create(array("code" => "NA", "name" => "Nambia"));
        Country::create(array("code" => "NU", "name" => "Nauru"));
        Country::create(array("code" => "NP", "name" => "Nepal"));
        Country::create(array("code" => "AN", "name" => "Netherland Antilles"));
        Country::create(array("code" => "NL", "name" => "Netherlands (Holland, Europe)"));
        Country::create(array("code" => "NV", "name" => "Nevis"));
        Country::create(array("code" => "NC", "name" => "New Caledonia"));
        Country::create(array("code" => "NZ", "name" => "New Zealand"));
        Country::create(array("code" => "NI", "name" => "Nicaragua"));
        Country::create(array("code" => "NE", "name" => "Niger"));
        Country::create(array("code" => "NG", "name" => "Nigeria"));
        Country::create(array("code" => "NW", "name" => "Niue"));
        Country::create(array("code" => "NF", "name" => "Norfolk Island"));
        Country::create(array("code" => "NO", "name" => "Norway"));
        Country::create(array("code" => "OM", "name" => "Oman"));
        Country::create(array("code" => "PK", "name" => "Pakistan"));
        Country::create(array("code" => "PW", "name" => "Palau Island"));
        Country::create(array("code" => "PS", "name" => "Palestine"));
        Country::create(array("code" => "PA", "name" => "Panama"));
        Country::create(array("code" => "PG", "name" => "Papua New Guinea"));
        Country::create(array("code" => "PY", "name" => "Paraguay"));
        Country::create(array("code" => "PE", "name" => "Peru"));
        Country::create(array("code" => "PH", "name" => "Philippines"));
        Country::create(array("code" => "PO", "name" => "Pitcairn Island"));
        Country::create(array("code" => "PL", "name" => "Poland"));
        Country::create(array("code" => "PT", "name" => "Portugal"));
        Country::create(array("code" => "PR", "name" => "Puerto Rico"));
        Country::create(array("code" => "QA", "name" => "Qatar"));
        Country::create(array("code" => "ME", "name" => "Republic of Montenegro"));
        Country::create(array("code" => "RS", "name" => "Republic of Serbia"));
        Country::create(array("code" => "RE", "name" => "Reunion"));
        Country::create(array("code" => "RO", "name" => "Romania"));
        Country::create(array("code" => "RU", "name" => "Russia"));
        Country::create(array("code" => "RW", "name" => "Rwanda"));
        Country::create(array("code" => "NT", "name" => "St Barthelemy"));
        Country::create(array("code" => "EU", "name" => "St Eustatius"));
        Country::create(array("code" => "HE", "name" => "St Helena"));
        Country::create(array("code" => "KN", "name" => "St Kitts-Nevis"));
        Country::create(array("code" => "LC", "name" => "St Lucia"));
        Country::create(array("code" => "MB", "name" => "St Maarten"));
        Country::create(array("code" => "PM", "name" => "St Pierre and Miquelon"));
        Country::create(array("code" => "VC", "name" => "St Vincent and Grenadines"));
        Country::create(array("code" => "SP", "name" => "Saipan"));
        Country::create(array("code" => "SO", "name" => "Samoa"));
        Country::create(array("code" => "AS", "name" => "Samoa American"));
        Country::create(array("code" => "SM", "name" => "San Marino"));
        Country::create(array("code" => "ST", "name" => "Sao Tome and Principe"));
        Country::create(array("code" => "SA", "name" => "Saudi Arabia"));
        Country::create(array("code" => "SN", "name" => "Senegal"));
        Country::create(array("code" => "SC", "name" => "Seychelles"));
        Country::create(array("code" => "SL", "name" => "Sierra Leone"));
        Country::create(array("code" => "SG", "name" => "Singapore"));
        Country::create(array("code" => "SK", "name" => "Slovakia"));
        Country::create(array("code" => "SI", "name" => "Slovenia"));
        Country::create(array("code" => "SB", "name" => "Solomon Islands"));
        Country::create(array("code" => "OI", "name" => "Somalia"));
        Country::create(array("code" => "ZA", "name" => "South Africa"));
        Country::create(array("code" => "ES", "name" => "Spain"));
        Country::create(array("code" => "LK", "name" => "Sri Lanka"));
        Country::create(array("code" => "SD", "name" => "Sudan"));
        Country::create(array("code" => "SR", "name" => "Suriname"));
        Country::create(array("code" => "SZ", "name" => "Swaziland"));
        Country::create(array("code" => "SE", "name" => "Sweden"));
        Country::create(array("code" => "CH", "name" => "Switzerland"));
        Country::create(array("code" => "SY", "name" => "Syria"));
        Country::create(array("code" => "TA", "name" => "Tahiti"));
        Country::create(array("code" => "TW", "name" => "Taiwan"));
        Country::create(array("code" => "TJ", "name" => "Tajikistan"));
        Country::create(array("code" => "TZ", "name" => "Tanzania"));
        Country::create(array("code" => "TH", "name" => "Thailand"));
        Country::create(array("code" => "TG", "name" => "Togo"));
        Country::create(array("code" => "TK", "name" => "Tokelau"));
        Country::create(array("code" => "TO", "name" => "Tonga"));
        Country::create(array("code" => "TT", "name" => "Trinidad and Tobago"));
        Country::create(array("code" => "TN", "name" => "Tunisia"));
        Country::create(array("code" => "TR", "name" => "Turkey"));
        Country::create(array("code" => "TU", "name" => "Turkmenistan"));
        Country::create(array("code" => "TC", "name" => "Turks and Caicos Is"));
        Country::create(array("code" => "TV", "name" => "Tuvalu"));
        Country::create(array("code" => "UG", "name" => "Uganda"));
        Country::create(array("code" => "UA", "name" => "Ukraine"));
        Country::create(array("code" => "AE", "name" => "United Arab Emirates"));
        Country::create(array("code" => "GB", "name" => "United Kingdom"));
        Country::create(array("code" => "US", "name" => "United States of America"));
        Country::create(array("code" => "UY", "name" => "Uruguay"));
        Country::create(array("code" => "UZ", "name" => "Uzbekistan"));
        Country::create(array("code" => "VU", "name" => "Vanuatu"));
        Country::create(array("code" => "VS", "name" => "Vatican City State"));
        Country::create(array("code" => "VE", "name" => "Venezuela"));
        Country::create(array("code" => "VN", "name" => "Vietnam"));
        Country::create(array("code" => "VB", "name" => "Virgin Islands (Brit)"));
        Country::create(array("code" => "VA", "name" => "Virgin Islands (USA)"));
        Country::create(array("code" => "WK", "name" => "Wake Island"));
        Country::create(array("code" => "WF", "name" => "Wallis and Futana Is"));
        Country::create(array("code" => "YE", "name" => "Yemen"));
        Country::create(array("code" => "ZR", "name" => "Zaire"));
        Country::create(array("code" => "ZM", "name" => "Zambia"));
        Country::create(array("code" => "ZW", "name" => "Zimbabwe"));
    }
}
